# Generated by Django 2.0 on 2022-07-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='google',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='linkedIn',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='twitter',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='card_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='card_title',
            field=models.TextField(max_length=200),
        ),
    ]
