# Generated by Django 2.0 on 2022-07-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20220728_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='google',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='linkedIn',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='twitter',
            field=models.CharField(max_length=200),
        ),
    ]
