# Generated by Django 2.0 on 2022-07-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_auto_20220728_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='main_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='card_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='google',
            field=models.CharField(max_length=300),
        ),
    ]
