# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 09:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Enter the name you would like to give this address.', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Please provide any extra description for this company.', null=True, verbose_name='Description')),
                ('vat', models.CharField(blank=True, help_text='VAT Registration', max_length=250, null=True, verbose_name='VAT Registration')),
                ('company_number', models.CharField(blank=True, help_text='Government allocated company number - e.g. HMRC Company Number', max_length=250, null=True, verbose_name='Company Number')),
                ('company_url', models.URLField(default='http://www.example.com', help_text='This is a unique URI to describe the callback used by the OAuth2 server', max_length=254, validators=[django.core.validators.URLValidator])),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Enter the name you would like to give this address.', max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Customer Addresses',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='addresses',
            field=models.ManyToManyField(related_name='addresses_company_set', to='account.CustomerAddress'),
        ),
    ]
