# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Enter your the address (line 1 of 4)', max_length=250, null=True, verbose_name='Address 1'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Enter your the address (line 2 of 4)', max_length=250, null=True, verbose_name='Address 2'),
        ),
    ]
