# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-29 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, height_field=250, max_length=50, upload_to='', width_field=250),
        ),
    ]
